rm -r /mnt/system_cache/NextCloud_conf/nextcloud/apps/*
rm -r /mnt/system_cache/NextCloud_conf/nextcloud/apps/.*
rm -r /mnt/system_cache/NextCloud_conf/nextcloud/apps-pkg/*
rm -r /mnt/system_cache/NextCloud_conf/nextcloud/apps-pkg/.*
rm -r /mnt/system_cache/NextCloud_conf/nextcloud/config/*
rm -r /mnt/system_cache/NextCloud_conf/nextcloud/config/.*
rm -r /mnt/system_cache/NextCloud_conf/nextcloud/data/*
rm -r /mnt/system_cache/NextCloud_conf/nextcloud/data/.*
rm -r /mnt/system_cache/NextCloud_conf/nextcloud/themes/*
rm -r /mnt/system_cache/NextCloud_conf/nextcloud/themes/.*
rm -r /mnt/system_cache/NextCloud_conf/php-fpm.d/.*
rm -r /mnt/system_cache/NextCloud_conf/php-fpm.d/.*
rm -r /mnt/system_cache/NextCloud_conf/home_root/db*
rm -r /mnt/system_cache/NextCloud_conf/home_root/nc*
rm -r /mnt/system_cache/NextCloud_conf/home_root/occ.sh
rm -r /mnt/system_cache/NextCloud_conf/nginx/*
rm -r /mnt/system_cache/NextCloud_conf/nginx/.*
rm -r /mnt/system_cache/NextCloud_mysql/*
rm -r /mnt/system_cache/NextCloud_mysql/.*
