rm -r /mnt/system-cache/Nextcloud_conf/nextcloud/apps/*
rm -r /mnt/system-cache/Nextcloud_conf/nextcloud/apps/.*
rm -r /mnt/system-cache/Nextcloud_conf/nextcloud/apps-pkg/*
rm -r /mnt/system-cache/Nextcloud_conf/nextcloud/apps-pkg/.*
rm -r /mnt/system-cache/Nextcloud_conf/nextcloud/config/*
rm -r /mnt/system-cache/Nextcloud_conf/nextcloud/config/.*
rm -r /mnt/system-cache/Nextcloud_conf/nextcloud/data/*
rm -r /mnt/system-cache/Nextcloud_conf/nextcloud/data/.*
rm -r /mnt/system-cache/Nextcloud_conf/nextcloud/themes/*
rm -r /mnt/system-cache/Nextcloud_conf/nextcloud/themes/.*
rm -r /mnt/system-cache/Nextcloud_conf/home_root/*
rm -r /mnt/system-cache/Nextcloud_conf/nginx/*
rm -r /mnt/system-cache/Nextcloud_conf/nginx/.*
rm -r /mnt/system-cache/Nextcloud_mysql/*
rm -r /mnt/system-cache/Nextcloud_mysql/.*